[tool.mypy]
exclude = "build/"

[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'

[tool.pytest.ini_options]
addopts = "-p no:ape_test"

[tool.isort]
line_length = 100
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["ape"]
known_first_party = ["ape_kong"]
multi_line_output = 3
use_parentheses = true
